services:
  - type: web
    name: render-chess
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        value: <your-database-url>
      - key: NODE_ENV
        value: production
